<?php
namespace app\admin\controller;

use phpmailer\PHPMailer;
use think\Controller;
use \app\common\validate\BusinessStore as StoreValidate;

class Business extends Controller
{
    /**
     * @var city 模型对象  validate 验证器对象
     */
    private $category;
    private $validate;

    /**
     * 初始化
     */
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->validate = new StoreValidate;
    }


    /****
     * 商户审查页面
     * @return mixed
     */
    public function index()
    {
        //1为审核通过的
        $results = model('Business')->getBusinessByStatus(1);
        $this->assign(['results'=>$results]);
        return $this->fetch();
    }

    /***
     * 商户申入驻请审查页面
     * @return mixed
     */
    public function apply()
    {
        $results = model('Business')->getBusinessByStatus();
        $this->assign(['results'=>$results]);
        return $this->fetch();
    }

    /****
     * 删除的商户页面
     * @return mixed
     */
    public function dellist()
    {
        //-1为已删除的
        $results = model('Business')->getBusinessByStatus(-1);
        $this->assign(['results'=>$results]);
        return $this->fetch();
    }

    /****
     * 商户详情页
     */
    public function detail()
    {
        //获取一级城市的数据
        $cities = model('City')->getFirstCity(0,true);
        //获取一级栏目的数据
        $categories = model('Category')->getFirstCategory(0,true);
        //获取商户数据
//        $bis_ID = $this->request->param('id');
        $bis_ID = input('get.id');
        if(!intval($bis_ID)>0){
            $this->error('输入的参数不合法');
        }
        $bisData = model('Business')->get($bis_ID);
        $storeData = model('BusinessStore')->get(['id'=>$bis_ID,'is_main'=>1]);
        $accountData = model('BusinessAccount')->get(['id'=>$bis_ID,'is_main'=>1]);
        $seCategoryData=getSeCategoryName($storeData['category_path']);
        $this->assign([
            'cities'=>$cities,
            'categories'=>$categories,
            'bisData'=> $bisData,
            'storeData'=>$storeData,
            'accountData'=>$accountData,
            'seCategoryData'=>empty($seCategoryData)?[]:$seCategoryData,
            ]);
        return $this->fetch();
    }

    /***
     * 商户总店用户状态更改 邮件提示
     * @param $id
     * @param $status
     * @param $email //邮箱
     * @param $title //邮件标题
     * @param $message //邮件内容
     * @return boolean
     */
    public function updateStatus($id,$status,$email,$title,$message)
    {
        $res = model('Business')->save(['status' => $status], ['id' => $id]);
        $store = model('BusinessStore')->save(['status' => $status], ['business_id' => $id]);
        $account = model('BusinessAccount')->save(['status' => $status], ['business_id' => $id]);
        if($res && $store && $account){
            \phpmailer\Email::send($email,$title,$message);
            return true;
        }else{
            return false;
        }
    }

    /**
     * 更改商户状态 status
     * status=0/1 待审核/通过
     * status=-1  已删除
     * status=2   未通过
     */
    public function status()
    {
        $data = $this->request->only(['id','status','email']);
        if (!$this->validate->scene('status')->check($data)){
            $this->error($this->validate->getError());
        }else{
            $sendEmail= false;
            if($data['status']==1){
                //status==1时,为通过
                $sendEmail = $this->updateStatus(
                    $data['id'],
                    $data['status'],
                    $data['email'],
                    'benefit购物平台商户申请审核通过',
                    '恭喜您，您在benefit购物平台中提交的商户申请已审核通过'
                );
            }
            if($data['status']==2){
                //status==2时,为不通过
                $sendEmail = $this->updateStatus(
                    $data['id'],
                    $data['status'],
                    $data['email'],
                    'benefit购物平台商户申请审核未通过',
                    '非常抱歉，您在benefit购物平台中提交的商户申请未通过'
                );
            }
            if($data['status']==-1){
                //status==-1时,为删除
                $sendEmail = $this->updateStatus(
                    $data['id'],
                    $data['status'],
                    $data['email'],
                    'benefit购物平台商户申请已被删除',
                    '非常抱歉，您在benefit购物平台中提交的商户申请已被删除'
                );
            }
            //更改成功并成功发送邮件时
            if($sendEmail){
                $this->success();
            }else{
                $this->error();
            }
        }
    }


    /*****分店申请模块********/

    /***
     * 商户申入驻请审查页面
     * @return mixed
     * @throws \think\exception\DbException
     */
    public function applyStore()
    {
        $results = model('BusinessStore')
            ->where([['status','=',0],['is_main','=',0]])
            ->paginate();
        $this->assign(['results'=>$results]);
        return $this->fetch();
    }


    /**
     * 更改商户分店状态 status
     * status=0/1 待审核/通过
     * status=-1  已删除
     * status=2   未通过
     */
    public function statusStore()
    {
        $data = $this->request->only(['id','status']);
        //根剧business_id搜索商户信息
        if (!validate('BusinessStore')->scene('status')->check($data)){
            $this->error(validate('BusinessStore')->getError());
        }else{
            $store = model('BusinessStore')->save(['status' => $data['status']], ['id' => $data['id']]);
            if($store){
                $this->success('更改分店状态成功');
            }else{
                $this->error('更改分店状态失败');
            }
        }
    }
}
