<?php
namespace app\admin\controller;

use think\Controller;
use \app\admin\validate\City as CityValidate;
use \app\common\model\City as CityModel;
use think\response\Json;


class City extends Controller
{
    /**
     * @var city 模型对象  validate 验证器对象
     */
    private $city;
    private $validate;

    /**
     * 初始化
     */
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->city = new CityModel;
        $this->validate = new CityValidate;
    }

    /**
     * 获取并显示表中为一级的城市 页面
     * parent_id为0为一级城市页面
     * paren_id其他为其对应的城市页面
     *
     * @return mixed
     */
    public function index()
    {
        //获取parent_id = id 用于获取父节点为id的节点
        $parent_id = $this->request->param('parent_id',0,'int');
        $cities = $this->city->getFirstCity($parent_id);
        $this->assign(['cities'=>$cities,'parentId'=>$parent_id]);
        return $this->fetch();
    }

    /**
     * 添加城市页面
     *
     * @return mixed
     */
    public function add()
    {
        //获取已存在的一级城市
        $parent_id = $this->request->param('parent_id',0,'int');
        $cities = $this->city->getFirstCity($parent_id,true);
        $this->assign(['cities'=>$cities]);
        return $this->fetch();
    }

    /**
     * 添加城市 保存
     *
     * @return mixed
     */
    public function save()
    {
        $data = $this->request->only(['name', 'uname','parent_id']);

        if (!$this->validate->scene('add')->check($data))
        {
            $this->error($this->validate->getError());
        } else {
            $this->city->addCity($data);
            $this->success('城市'.$data['name'].$data['uname'].'添加成功');
        }
    }

    /**
     * 获取修改城市数据页面
     *
     * @param $id 数据id
     * @return mixed
     */
    public function edit($id)
    {
        if(intval($id)<1)
        {
            $this->error('参数不合法');
        }else{
            $city = $this->city->get($id);
            $cities = $this->city->getFirstCity(0,true);
            $this->assign(['city'=>$city,'cities'=>$cities]);
        }
        return $this->fetch();
    }

    /**
     * 更新城市信息 name 名称 uname 英文名称 parent_id 父id
     *
     * @param int $id
     * @return mixed
     */
    public function update($id){
        $city = $this->city->get($id);
        $data=$this->request->param();
        if(!$this->validate->scene('update')->check($data)){
            $this->error($this->validate->getError);
        }else{
            // 只允许更新指定的字段数据
            $city->allowField(['name','uname','parent_id'])
                ->save($data);
            $this->success('城市[' . $city->name . ']更新成功');
        }
    }

    /**
     * 更改城市 listorder
     *
     * @return mixed
     */
    public function listorder(){
        $data = $this->request->only(['id','listorder']);
        if(!$this->validate->scene('listorder')->check($data)) {
            $this->error($this->validate->getError());
        }else{
            $res=$this->city->save(['listorder'=>$data['listorder']],['id'=>$data['id']]);
            if($res){
                $this->result($_SERVER['HTTP_REFERER'],1,'更新成功');
            }else{
                $this->result($_SERVER['HTTP_REFERER'],0,'更新失败');
            }
        }
    }


    /**
     * 更改状态 status
     * status=0/1 待审查/正常
     * status=-1  已删除
     *
     */
    public function status(){
        $data = $this->request->only(['id','status']);
        if (!$this->validate->scene('status')){
            $this->error($this->validate->getError());
        }else{
            //当不为删除时 即status = 0/1时
            if($data['status']!=-1){
                $res = $this->city->save(['status'=>$data['status']],['id'=>$data['id']]);
                if($res){
                    $this->success('状态更新成功');
                }else{
                    $this->success('状态更新失败');
                }
            }else{  //当删除时  status = -1
                //判断是否存在子分类
                $results=$this->city->where('parent_id',$data['id'])->select();
                if(count($results)>0){
                    $this->city->save(['status' => $data['status']], ['id' => $data['id']]);
                    foreach($results as $key => $result){
                        $this->city->update(['status' => $data['status'],'id' => $result->id]);
                    }
                    $this->success('删除成功');
                }else{
                    $res = $this->city->save(['status' => $data['status']], ['id' => $data['id']]);
                    if ($res) {
                        $this->success('删除成功');
                    } else {
                        $this->success('删除失败');
                    }
                }
            }
        }
    }
}
