<?php
namespace app\admin\controller;

use think\Controller;
use app\common\validate\Featured as FeaturedValidate;

class Featured extends Controller
{
    private $validate;
    /***
     *
     */
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->validate = new FeaturedValidate;
    }

    /****
     * 推荐位列表
     * @return mixed
     */
    public function index(){
        //获取推荐位类别
        $types = config('featured.featured_type');
        $map = [];
        if($this->request->isGet()){
            $type = input('get.type');
            if(!empty($type)){
                $map[] = ['type','=',$type];
            }
        }
        $results = model('Featured')->getFeaturedsByType($map);

        $this->assign([
            'types'=>$types,
            'results'=>$results,
            'type'=>empty($type)?'':$type,
            ]);
        return $this->fetch();
    }

    /****
     * 添加推荐位
     * @return mixed
     */
    public function add(){
        if($this->request->isPost()){
            $data = input('post.');
            //校验
            $this->validate->scene('add')->check($data);
            $id = model('Featured')->add($data);
            if($id){
                $this->success('添加成功');
            }else{
                $this->error('添加失败');
            }
        }else{
            //推荐位类别
            $types = config('featured.featured_type');
            $this->assign(['types'=>$types]);
            return $this->fetch();
        }
    }

    /****
     * 团购商品详情页
     */
    public function detail()
    {
        //获取商户数据
//        $bis_ID = $this->request->param('id');
        $featured_ID = input('get.id');
        if(!intval($featured_ID)>0){
            $this->error('输入的参数不合法');
        }
        $featuredData = model('Featured')->get(['id'=>$featured_ID]);
        $types = config('featured.featured_type');
        $this->assign([
            'featuredData'=>$featuredData,
            'types'=>$types
        ]);
        return $this->fetch();
    }

    /**
     * 更改状态 status
     * status=-1，0，1，2
     */
    public function status()
    {
        $data = $this->request->only(['id','status']);
        if (!$this->validate->scene('status')->check($data)){
            $this->error($this->validate->getError());
        }else{
            $res = model('Featured')->save(['status' => $data['status']], ['id' => $data['id']]);
            if ($res) {
                $this->success('状态更新成功');
            } else {
                $this->success('状态更新失败');
            }

        }
    }
}
