<?php
namespace app\index\controller;

use think\Controller;
use think\captcha\Captcha;


class Base extends Controller
{
    public $default_city = '';
    public $user = '';
    /***
     * 初始化
     */
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        //获取所有一级城市
        $cities = model('City')->getFirstCity(0,true);
        //获取选中的城市/并默认选中的城市为当前城市
        $this->getDefaultCity($cities);
        //获取所有分类数据（一级以及二级）
        $categories=$this->getRecommendCategories();


        $this->assign([
            'default_city'=> $this->default_city,
            'cities'=>$cities,
            'categories'=>$categories,
            'user'=>$this->getLoginUser(),

            //获取当前类的类名，用于子类对应获取css
            'controller'=>strtolower(request()->controller()),
            //当前页标题
            'title'=>'benefit团购网'
        ]);
    }

    /***
     * 获取已登陆的用户的数据
     * @return bool|mixed
     */
    public function getLoginUser(){
        if(!$this->user){
            $this->user = session('loginUser','','user');
        }
        return $this->user;
    }

    /****
     * 获取选中的城市/默认选中的城市
     * @param $cities
     * @throws \think\db\exception\DataNotFoundException
     * @throws \think\db\exception\ModelNotFoundException
     * @throws \think\exception\DbException
     */
    public function getDefaultCity($cities){
        foreach ($cities as $city){
            //$city：对象格式 将对象转换为数组
            $city = $city->toArray();
            if($city['is_default']==1){
                $defaultuname=$city['uname'];
                break;
            };
        }
        $defaultuname = isset($defaultuname) ? $defaultuname :'Shen Zhen';
        if(session('cityUname','','benfefit') && !input('get.city')){
            $cityuname = session('cityUname','','benfefit');
        }else{
            $cityuname = input('get.city',$defaultuname,'trim');
            session('cityUname',$cityuname,'benfefit');
        }

        $this->default_city = model('City')->where(['uname'=>$cityuname])->find();
    }

    /***
     * 获取用于显示的一级分类以及二级分类
     * @return array
     */
    public function getRecommendCategories(){
        $parentIds = [];
        $sedCategoryArr = [];
        $recomCategoryArr = [];   //一级分类和二级分分类数据
        //获取5条按listorder和id排序的一级分类
        $categories = model('Category')->getRecommendCategoriesByParentId(0,5);
        //获取显示的一级分类的id
        foreach ($categories as $category){
            $parentIds[] = $category->id;
        }

        //根据一级分类的id 获取二级分类
        $sedCategories = model('Category')->getNormalCategoriesByParentId($parentIds);
        foreach ($sedCategories as $sedCategory){
            $sedCategoryArr[$sedCategory->parent_id][] = [
                'id' => $sedCategory->id,
                'name' => $sedCategory->name,
            ];
        }

        foreach ($categories as $category){
            //一级分类和二级分分类数据  第一个参数是一级分类的name
            $recomCategoryArr[$category->id] = [
                $category->name,
                empty($sedCategoryArr[$category->id])?[] : $sedCategoryArr[$category->id]
                ];
        }

        return $recomCategoryArr;
    }
}
