<?php
/**
 * Created by PhpStorm.
 * User: zhangronghua
 * Date: 2019/11/16
 * Time: 5:55 AM
 */

namespace app\bis\controller;


use think\Controller;

class Base extends Controller
{
    public $account;
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $isLogin = $this->isLogin();
        if(!$isLogin){
            $this->redirect('login/index');
        }
        $this->assign(['user'=>$this->getAccountLogin()]);
    }

    public function isLogin()
    {
        $account = $this->getAccountLogin();
        if($account && $account->id ) {
           return true;
        }else{
            return false;
        }
    }

    /***
     * @return mixed 返回已登陆用户的数据
     */
    public function getAccountLogin()
    {
        if(!$this->account){
            $this->account = session('bisAccount','','business');
        }
        return $this->account;
    }

}