<?php
namespace app\bis\controller;

use app\common\model\BusinessAccount;
use think\Controller;
use app\common\validate\BusinessAccount as AccountValidta;

class Login extends Controller
{
    private $validate;
    public function initialize()
    {
        $this->validate = new AccountValidta;
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    public function index(){
        //判断是否为登陆操作 若用户存在且密码正确 跳着到平台界面
        if(request()->isPost()){
            $data = input('post.');
            if(!$this->validate->scene('account')->check($data)) {
                $this->error($this->validate->getError());
            }
            $res = model('BusinessAccount')->get(['username'=>$data['username']]);
            if(!$res){
                $this->error('用户名不存在');
            }
            if($res['status']!=1){
                $this->error('该用户审核未通过');
            }
            if(md5($data['password'].$res['code'])!= $res['password']){
                $this->error('密码不正确');
            }else{
                //更改登陆时间
                model('businessAccount')->save(['last_login_time'=>time()],['id'=>$res['id']]);
                //保存用户信息 key value 作用域
                session('bisAccount',$res,'business');
                //登陆成功
                $this->success('登陆成功','index/index');
            }
        } else{//否则渲染登陆界面
            //获取session
            $account = session('bisAccount','','business');
            //判断是否已登陆
            if($account && $account->id){
                $this->redirect('index/index');
            }
            return $this->fetch();

        }
    }
    /***
     * 退出
     */
    public function logout(){
        session(null,'business');
        $this->redirect('login/index');
    }
}