<?php
namespace app\bis\controller;

use think\Controller;
use app\common\validate\Business;

class Store extends Base
{
    private $validate;
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->validate = new Business;
    }

    /***
     * 店铺管理首页
     * @return mixed
     */
    public function index()
    {
//        $data = model('BusinessStore')
//                ->where(['status'=>1])
//                ->select();
        $bisID = $this->getAccountLogin()->business_id;
        $bisStores = model('BusinessStore')->getStoreByStatus($bisID);

        return $this->fetch('',['bisStores'=>$bisStores]);
    }

    /****
     * 分店详情页
     */
    public function detail()
    {
        //获取一级城市的数据
        $cities = model('City')->getFirstCity(0,true);
        //获取一级栏目的数据
        $categories = model('Category')->getFirstCategory(0,true);
        //获取商户数据
//        $bis_ID = $this->request->param('id');
        $sotre_ID = input('get.id');
        if(!intval($sotre_ID)>0){
            $this->error('输入的参数不合法');
        }
        $storeData = model('BusinessStore')->get(['id'=>$sotre_ID]);
        $seCategoryData=getSeCategoryName($storeData['category_path']);
        $this->assign([
            'cities'=>$cities,
            'categories'=>$categories,
            'storeData'=>$storeData,
            'seCategoryData'=>empty($seCategoryData)?[]:$seCategoryData,
        ]);
        return $this->fetch();
    }


    /**
     * 更改状态 status
     * status=-1  为删除
     */
    public function status()
    {
        $data = $this->request->only(['id','status']);
        if (!$this->validate->scene('status')->check($data)){
            $this->error($this->validate->getError());
        }else{
            if($data['status']==-1){
                //status==-1时,为删除
                $res = model('BusinessStore')->save(['status'=>$data['status']],['id'=>$data['id']]);
                if($res){
                    $this->success('状态更新成功');
                }else{
                    $this->success('状态更新失败');
                }
            }
        }
    }


    /**
     * 添加分店页面以及添加分店功能
     * @return mixed
     */
    public function add()
    {
        //判断是否为添加操作
        if($this->request->isPost()){

            $data = input('post.');
            $bisID = $this->getAccountLogin()->business_id;

            //校验数据
            if(!$this->validate->scene('store')->check($data)){
                $this->error($this->validate->getError());
            }
            //获取经纬度  map
            $lnglat=\Map::getLngLat($data['address']);
            if(empty(($lnglat)) || $lnglat['status'] != 0 || $lnglat['result']['precise']!=1){
                $this->error('无检索地址对应位置或匹配地址不精准');
            }else{
                $xpoint = empty($lnglat['result']['location']['lng'])?'':$lnglat['result']['location']['lng']; //经度
                $ypoint = empty($lnglat['result']['location']['lat'])?'':$lnglat['result']['location']['lat']; //纬度
            }

            //粘合二级分类
            $data['cat'] = '';
            if(!empty($data['se_category_id'])){
                $data['cat'] = implode('|',$data['se_category_id']);
            }
            //总店相关信息校验
            //总店相关信息入库

            $storeData = [
                'business_id' => $bisID,
                'name' => $data['name'],
                'tel' => $data['tel'],
                'contact' => $data['contact'],
                'logo' => $data['logo'],
                'category_id' => $data['category_id'],
                'category_path' => empty($data['se_category_id']) ? $data['category_id'] : $data['category_id'] . ',' . $data['cat'],
                'address' => $data['address'],
                'open_time' => $data['open_time'],
                'content' => empty($data['content']) ? '' : $data['content'],
                'is_main' => 0,
                'xpoint' => $xpoint, //城市完整路径,
                'ypoint' => $ypoint, //城市完整路径,
                'city_id' => $data['city_id'],
                'city_path' => empty($data['se_city_id']) ? $data['city_id'] : $data['city_id'] . ',' . $data['se_city_id'], //城市完整路径
            ];

            $storeID = model('BusinessStore')->add($storeData);
            if($storeID){
                return $this->success('门店申请成功');
            }else{
                return $this->success('门店申请失败');
            }
        }else{
            $cities = model('City')->getFirstCity(0,true);
            $categories = model('Category')->getFirstCategory(0,true);
            $this->assign(['cities'=>$cities,'categories'=>$categories]);
            return $this->fetch();
        }
    }
}
