<?php
/**
 * 获取二级分类接口
 */
namespace app\api\controller;

use think\Controller;
use \app\common\model\Category as CategoryModel;
use \app\common\validate\Category as CategoryValidate;
use think\response\Json;

class Category extends Controller
{
    /**
     * @var city 模型对象  validate 验证器对象
     */
    private $category;
    private $valid;

    /**
     * 初始化
     */
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->category = new CategoryModel;
        $this->valid = new CategoryValidate;
    }

    /**
     * 获取并显示表中的分类 页面
     * parent_id为0为一级分类页面
     * paren_id其他为其对应的子分类页面
     *
     * @return mixed
     */
    public function getCategoryByParentId()
    {
        //获取parent_id = id 用于获取父节点为id的节点
        $id = $this->request->param('id');
        if(!$id){
            $this->error('参数不合法');
        }
        //传入id 获取为parent_id为id的值,true为状态为正常的节点
        $categories = $this->category->getFirstCategory($id,true);
        if(!$categories){
            return show(0,'error');
        }
        return show(1,'success',$categories);
    }

    /**
     * 更改分类排序
     * @return mixed
     */
    public function listorder()
    {
        $data = $this->request->param();
        if (!$this->valid->scene('listorder')->check($data)) {
            $this->error($this->valid->getError());
        }
        $res = $this->category->save(['listorder' => $data['listorder']], ['id' => $data['id']]);
        if ($res) {
            $this->result($_SERVER['HTTP_REFERER'],1,'更新成功');
        } else {
            $this->result($_SERVER['HTTP_REFERER'],0,'更新失败');
        }
    }
}
